config/routes.rb
Rails.application.routes.draw do

  root 'gallery#index'
  get 'search' => 'gallery#search'

  devise_for :users

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :authenticate_user!
end

app/controllers/gallery_controller.rb
class GalleryController < ApplicationController
  require 'flickr_config'
  require 'flickraw'

  FlickRaw.api_key = FlickrConfig.config[:key]
  FlickRaw.shared_secret = FlickrConfig.config[:secret]

  def index
  end

  def search
    query_string = params[:q] && params[:q].strip || ''
    if (query_string == '')
      redirect_to action: 'index'
      return
    end

    @photos = get_recent_photos query_string

    if @photos == []
      redirect_to root_url, alert: 'Nothing found!'
    end
  end

  private

  def get_recent_photos query_string
    if query_string == nil ||
        (query_string && query_string.strip!) == ''
      return []
    end

    list = flickr.photos.search tags: query_string, per_page: 20

    res_photos = []

    threads = []
    list.each do |e|
      threads << Thread.new do
        title = e.title
        id = e.id
        secret = e.secret
        info = flickr.photos.getInfo photo_id: id, secret: secret

        flickr.photos.getInfo photo_id: id, secret: secret

        res_photos << {
          title: title,
          square: FlickRaw.url_s(info),
          big: FlickRaw.url_b(info)
        }
      end
    end

    threads.map(&:join)

    res_photos
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gallery_helper.rb
module GalleryHelper
end

app/views/gallery/_photos.html.erb
<% @photos.each do |p| %>
  <%= link_to p[:big], title: p[:title] do %>
    <%= image_tag p[:square], alt: p[:title] %>
  <% end %>
<% end %>

app/views/gallery/index.html.erb
<form action="<%= search_url %>" method=get>
  <div class="input-group">
    <input id="q" name="q" class=form-control placeholder="Search query..."/>
    <span class="input-group-btn">
      <button class="btn btn-default" type="button">Search</button>
    </span>
  </div><!-- /input-group -->
</form>

app/views/gallery/search.html.erb
<div id="gallery">
  <% if @photos == [] %>
    <p>
      Nothing found :(
    </p>
  <% else %>
    <%= render 'photos' %>
  <% end %>
</div>
<script>
  (function($){
    $(document).ready(function(){
      $('#gallery').magnificPopup({
        delegate: 'a',
        type: 'image',
        tLoading: 'Loading image #%curr%...',
        mainClass: 'mfp-img-mobile',
        gallery: {
          enabled: true,
          navigateByImgClick: true,
          preload: [0,1] // Will preload 0 - before current, and 1 after the current image
        },
        image: {
          tError: '<a href="%url%">The image #%curr%</a> could not be loaded.',
          titleSrc: function(item) {
            return item.el.attr('title');
          }
        }
      });
    });
  })(jQuery);
</script>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div role="alert" class="alert alert-<%= name == 'notice' ? "success" : "danger" %>">
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Flickr Photos", root_path, :class => 'navbar-brand' %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li>
          <%= link_to 'Logout', destroy_user_session_path, :method=>'delete' %>
          </li>
        <% else %>
          <li>
          <%= link_to 'Login', new_user_session_path %>
          </li>
        <% end %>
        <% if user_signed_in? %>
          <li>
          <%= link_to 'Edit account', edit_user_registration_path %>
          </li>
        <% else %>
          <li>
          <%= link_to 'Sign up', new_user_registration_path %>
          </li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Flickr Photos" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Flickr Photos" %>">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body class="<%= controller_name %> <%= action_name %>">
    <%= render 'layouts/navigation' %>
    <%= render 'layouts/messages' %>
    <div id="main" role="main">
      <div class="container">
        <div class="content">
           <div class="row">
            <div class="span12">
              <%= yield %>
            </div>
          </div>
          <footer>
          </footer>
        </div>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>